#!/usr/bin/env python3
"""Strip AI/generator fingerprints from Microsoft Office files (.docx, .pptx, .xlsx).

Removes the tell-tale signs that a file was produced or modified by a script
(python-docx, python-pptx, openpyxl, LibreOffice, etc.) rather than by Word
/ PowerPoint / Excel itself.

Usage:
  sanitize.py <file>                         # sanitize in place, backup as .backup.<ext>
  sanitize.py <file> --output <new-file>     # write to new path, keep original
  sanitize.py <file> --no-backup             # in-place, no backup
  sanitize.py <file> --json                  # emit JSON report
  sanitize.py <file> --dry-run               # inspect only, no write

Works across:
- .docx  — normalizes <w:p> paraId/rsid, refreshes app.xml stats, core.xml timestamp
- .pptx  — normalizes <p:sld> metadata, refreshes app.xml, strips script-generator tags
- .xlsx  — refreshes app.xml Application field, core.xml timestamp
"""
import argparse, json, os, random, re, shutil, sys, tempfile, zipfile
from datetime import datetime, timezone

FORENSIC_STRINGS = [
    "python-docx", "python-pptx", "openpyxl", "python-openxml",
    "LibreOffice", "libreoffice",
    "Apache POI",
    "Aspose",
    "Generated by",
    "anthropic", "Anthropic",
    "claude", "Claude",
    "chatgpt", "ChatGPT",
    "openai", "OpenAI",
    "gpt-4", "gpt-3",
]


def hex8():
    return f"{random.randint(0, 0xFFFFFFFF):08X}"


def now_w3cdtf():
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def extract_zip(zip_path, target):
    with zipfile.ZipFile(zip_path) as z:
        z.extractall(target)


def repack_zip(source_dir, zip_path):
    if os.path.exists(zip_path):
        os.remove(zip_path)
    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as z:
        for root, _, files in os.walk(source_dir):
            for f in files:
                full = os.path.join(root, f)
                rel = os.path.relpath(full, source_dir).replace(os.sep, "/")
                z.write(full, rel)


def scan_forensic_strings(work):
    """Return list of (file, needle) pairs for any suspicious strings found."""
    hits = []
    for root, _, files in os.walk(work):
        for f in files:
            full = os.path.join(root, f)
            if not (f.endswith(".xml") or f.endswith(".rels")):
                continue
            try:
                with open(full, "r", encoding="utf-8", errors="ignore") as fh:
                    content = fh.read()
            except Exception:
                continue
            for needle in FORENSIC_STRINGS:
                if needle in content:
                    hits.append((os.path.relpath(full, work), needle))
    return hits


def strip_forensic_strings(work, strings=None):
    """Remove/replace forensic strings in any XML or rels file in the work dir."""
    replacements = []
    needles = strings or FORENSIC_STRINGS
    for root, _, files in os.walk(work):
        for f in files:
            full = os.path.join(root, f)
            if not (f.endswith(".xml") or f.endswith(".rels")):
                continue
            try:
                with open(full, "r", encoding="utf-8", errors="ignore") as fh:
                    content = fh.read()
            except Exception:
                continue
            new_content = content
            for needle in needles:
                if needle in new_content:
                    if needle.lower() in ("libreoffice",):
                        new_content = new_content.replace(needle, "Microsoft Office Word")
                    else:
                        new_content = re.sub(
                            rf"{re.escape(needle)}[^<\"']*",
                            "",
                            new_content,
                        )
                    replacements.append((os.path.relpath(full, work), needle))
            if new_content != content:
                with open(full, "w", encoding="utf-8") as fh:
                    fh.write(new_content)
    return replacements


def fix_docx_paragraphs(work):
    """Add w14:paraId / rsid attributes to bare <w:p> tags."""
    doc_path = os.path.join(work, "word", "document.xml")
    if not os.path.exists(doc_path):
        return 0, []
    with open(doc_path, "r", encoding="utf-8") as f:
        content = f.read()

    bare_count = len(re.findall(r"<w:p>", content))
    if bare_count == 0:
        return 0, []

    new_rsids = [hex8(), hex8()]
    counter = {"n": 0}

    def repl(m):
        counter["n"] += 1
        rsid = new_rsids[counter["n"] % len(new_rsids)]
        return (
            f'<w:p w14:paraId="{hex8()}" w14:textId="77777777" '
            f'w:rsidR="{rsid}" w:rsidRDefault="{rsid}">'
        )

    new_content = re.sub(r"<w:p>", repl, content)
    with open(doc_path, "w", encoding="utf-8") as f:
        f.write(new_content)

    # Register rsids in settings.xml
    settings_path = os.path.join(work, "word", "settings.xml")
    if os.path.exists(settings_path):
        with open(settings_path, "r", encoding="utf-8") as f:
            settings = f.read()
        rsid_entries = "".join(f'<w:rsid w:val="{r}"/>' for r in new_rsids)
        if "</w:rsids>" in settings:
            settings = settings.replace("</w:rsids>", rsid_entries + "</w:rsids>", 1)
            with open(settings_path, "w", encoding="utf-8") as f:
                f.write(settings)

    return bare_count, new_rsids


def refresh_app_xml(work, doc_content=None):
    """Recompute TotalTime/Pages/Words/Chars from document content,
    plausibly. Force Application to a normal value."""
    app_path = os.path.join(work, "docProps", "app.xml")
    if not os.path.exists(app_path):
        return {}
    with open(app_path, "r", encoding="utf-8") as f:
        app = f.read()

    # Force Application field to Word if it's a script generator
    app = re.sub(
        r"<Application>[^<]*</Application>",
        "<Application>Microsoft Office Word</Application>",
        app,
    )
    if "<AppVersion>" not in app:
        app = app.replace("</Properties>", "<AppVersion>16.0000</AppVersion></Properties>")
    else:
        app = re.sub(r"<AppVersion>[^<]*</AppVersion>", "<AppVersion>16.0000</AppVersion>", app)

    # Aggregate all visible text from every XML in word/, ppt/, xl/
    all_text = []
    for root, _, files in os.walk(work):
        for fn in files:
            if not fn.endswith(".xml"):
                continue
            full = os.path.join(root, fn)
            rel = os.path.relpath(full, work).replace(os.sep, "/")
            if not (rel.startswith("word/") or rel.startswith("ppt/") or rel.startswith("xl/")):
                continue
            try:
                with open(full, "r", encoding="utf-8", errors="ignore") as fh:
                    content = fh.read()
            except Exception:
                continue
            # drawingml/wordprocessingml text tags
            all_text.extend(re.findall(r"<(?:w|a):t[^>]*>([^<]*)</(?:w|a):t>", content))
            # xlsx inline strings
            all_text.extend(re.findall(r"<t[^>]*>([^<]*)</t>", content))
    joined = " ".join(all_text)
    words = len(joined.split())
    chars_ns = sum(1 for c in joined if not c.isspace())
    chars_ws = len(joined)
    pages = max(1, chars_ws // 2800)
    lines = max(1, chars_ws // 75)
    para_count = 0
    doc_xml = os.path.join(work, "word", "document.xml")
    if os.path.exists(doc_xml):
        with open(doc_xml, "r", encoding="utf-8") as fh:
            para_count = len(re.findall(r"<w:p[ >]", fh.read()))
    total_time = random.randint(90, 240)

    def set_field(src, tag, value):
        if f"<{tag}>" in src:
            return re.sub(rf"<{tag}>[^<]*</{tag}>", f"<{tag}>{value}</{tag}>", src)
        return src

    app = set_field(app, "TotalTime", total_time)
    app = set_field(app, "Pages", pages)
    app = set_field(app, "Words", words)
    app = set_field(app, "Characters", chars_ns)
    app = set_field(app, "CharactersWithSpaces", chars_ws)
    app = set_field(app, "Lines", lines)
    if para_count:
        app = set_field(app, "Paragraphs", para_count)

    with open(app_path, "w", encoding="utf-8") as f:
        f.write(app)

    return {
        "total_time": total_time,
        "words": words,
        "characters": chars_ns,
        "pages": pages,
    }


def refresh_core_xml(work, creator=None, last_modified_by=None, modified=None):
    core_path = os.path.join(work, "docProps", "core.xml")
    if not os.path.exists(core_path):
        return {}
    with open(core_path, "r", encoding="utf-8") as f:
        core = f.read()

    new_modified = modified or now_w3cdtf()
    core = re.sub(
        r"(<dcterms:modified[^>]*>)[^<]+(</dcterms:modified>)",
        rf"\g<1>{new_modified}\g<2>",
        core,
    )

    # Bump revision count to show activity
    m = re.search(r"<cp:revision>(\d+)</cp:revision>", core)
    if m:
        new_rev = int(m.group(1)) + random.randint(2, 5)
        core = re.sub(r"<cp:revision>\d+</cp:revision>", f"<cp:revision>{new_rev}</cp:revision>", core)

    if creator is not None:
        core = re.sub(r"<dc:creator>[^<]*</dc:creator>", f"<dc:creator>{creator}</dc:creator>", core)
    if last_modified_by is not None:
        core = re.sub(
            r"<cp:lastModifiedBy>[^<]*</cp:lastModifiedBy>",
            f"<cp:lastModifiedBy>{last_modified_by}</cp:lastModifiedBy>",
            core,
        )

    with open(core_path, "w", encoding="utf-8") as f:
        f.write(core)

    return {"modified": new_modified}


def sanitize(path, output=None, no_backup=False, dry_run=False, creator=None, last_modified_by=None):
    ext = os.path.splitext(path)[1].lower()
    if ext not in (".docx", ".pptx", ".xlsx"):
        raise ValueError(f"Unsupported extension: {ext}. Supports .docx, .pptx, .xlsx.")

    report = {
        "file": path,
        "format": ext.lstrip("."),
        "dry_run": dry_run,
    }

    work = tempfile.mkdtemp(prefix="deai-office-")
    try:
        extract_zip(path, work)

        # 1. Forensic string scan (always)
        forensic_hits_before = scan_forensic_strings(work)
        report["forensic_strings_found"] = [
            {"file": f, "needle": n} for f, n in forensic_hits_before
        ]

        if dry_run:
            # Count bare paragraphs for reporting
            if ext == ".docx":
                doc = os.path.join(work, "word", "document.xml")
                if os.path.exists(doc):
                    with open(doc, "r", encoding="utf-8") as f:
                        report["bare_w_p_count"] = len(re.findall(r"<w:p>", f.read()))
            return report

        # 2. Fix bare paragraphs (docx only; pptx/xlsx don't use rsid pattern)
        if ext == ".docx":
            bare_count, new_rsids = fix_docx_paragraphs(work)
            report["paragraphs_patched"] = bare_count
            report["new_rsids"] = new_rsids

        # 3. Strip forensic strings
        replacements = strip_forensic_strings(work)
        report["forensic_strings_stripped"] = [
            {"file": f, "needle": n} for f, n in replacements
        ]

        # 4. Refresh app.xml
        app_stats = refresh_app_xml(work)
        report["app_xml"] = app_stats

        # 5. Refresh core.xml
        core_stats = refresh_core_xml(
            work,
            creator=creator,
            last_modified_by=last_modified_by,
        )
        report["core_xml"] = core_stats

        # Determine output path and handle backup
        out_path = output or path
        if not output and not no_backup:
            base, ex = os.path.splitext(path)
            backup = f"{base}.backup{ex}"
            shutil.copy2(path, backup)
            report["backup"] = backup

        repack_zip(work, out_path)
        report["output"] = out_path
        report["output_size"] = os.path.getsize(out_path)
    finally:
        shutil.rmtree(work, ignore_errors=True)

    return report


def format_report(report):
    lines = []
    lines.append("De-AI sanitize complete.")
    lines.append(f"- File:            {report['file']}")
    lines.append(f"- Format:          {report['format']}")
    if "backup" in report:
        lines.append(f"- Backup:          {report['backup']}")
    if "output" in report:
        lines.append(f"- Output:          {report['output']}  ({report['output_size']} bytes)")
    if "paragraphs_patched" in report:
        lines.append(f"- Bare <w:p> tags: {report['paragraphs_patched']} patched")
        if report.get("new_rsids"):
            lines.append(f"  rsids added:     {', '.join(report['new_rsids'])}")
    hits = report.get("forensic_strings_found", [])
    if hits:
        lines.append(f"- Forensic strings: {len(hits)} occurrence(s) found")
        for h in hits[:10]:
            lines.append(f"    {h['file']}: {h['needle']}")
        if len(hits) > 10:
            lines.append(f"    ... and {len(hits)-10} more")
        lines.append(f"  Stripped:        {len(report.get('forensic_strings_stripped', []))}")
    else:
        lines.append("- Forensic strings: none found")
    app = report.get("app_xml", {})
    if app:
        lines.append(
            f"- app.xml stats:   words={app.get('words')} chars={app.get('characters')} "
            f"pages={app.get('pages')} time={app.get('total_time')}min"
        )
    core = report.get("core_xml", {})
    if core:
        lines.append(f"- core.xml modified: {core.get('modified')}")
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("file", help="Path to .docx, .pptx, or .xlsx")
    ap.add_argument("--output", help="Write sanitized copy to this path (keeps original)")
    ap.add_argument("--no-backup", action="store_true", help="In-place, no backup copy")
    ap.add_argument("--dry-run", action="store_true", help="Inspect only, do not modify")
    ap.add_argument("--json", action="store_true", help="Emit JSON report")
    ap.add_argument("--creator", help="Override dc:creator in core.xml")
    ap.add_argument("--last-modified-by", help="Override cp:lastModifiedBy in core.xml")
    args = ap.parse_args()

    report = sanitize(
        args.file,
        output=args.output,
        no_backup=args.no_backup,
        dry_run=args.dry_run,
        creator=args.creator,
        last_modified_by=args.last_modified_by,
    )

    if args.json:
        print(json.dumps(report, indent=2))
    else:
        print(format_report(report))


if __name__ == "__main__":
    main()
